### ISSUE TITLE
It seems that the Probablistic method belongs to Fine Registration (Local Registration).

### ISSUE THREAD

**Issue by Sunzhiliang** [XuyangBai/awesome-point-cloud-registration#3]
It seems that the Probablistic methods belong to Fine Registration (Local Registration), like CPD, GMM-Tree, FilterReg. They are more accurate than ICP-like methods.

**Comment by XuyangBai** [comment]
I agree that some early works of the probabilistic methods should be categorized into Fine Registration, while recently proposed ones (e.g DeepGMR, PointGMM) perform the registration without the initialization and with "arbitrary" displacement. And the probabilistic technique should not limit to local or global registration, I will consider reorganizing the taxonomy to be more precise. Thanks a lot for your notice!
