### ISSUE TITLE
Colored-ICP

### ISSUE THREAD

**Issue by yiyangd** [XuyangBai/awesome-point-cloud-registration#4]
Hi Xuyang,

Thank you so much for this awesome paper collection! I am wondering if Colored-ICP[1] should be in this list?

[1] J. Park, Q.-Y. Zhou, and V. Koltun, Colored Point Cloud Registration Revisited, ICCV, 2017.

**Comment by XuyangBai** [comment]
Thanks a lot, I have added it to the list :)
